# Generated by Django 5.1.2 on 2025-03-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('UPI', 'UPI')], default='', max_length=16, null=True),
        ),
    ]
