# Generated by Django 5.1.2 on 2025-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='remarks',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
