# Generated by Django 5.1.2 on 2025-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_cart_status_cartitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
