# Generated by Django 5.1.2 on 2025-02-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('desc', models.TextField(null=True)),
                ('company', models.CharField(max_length=10)),
                ('types', models.CharField(choices=[('Hard Tennis Bats', 'HardTennisBats'), ('Soft Tennis Bats', 'SoftTennisBats'), ('Custom Bats', 'CustomBats')], default=None, max_length=40)),
                ('og_price', models.DecimalField(decimal_places=0, max_digits=4)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('size', models.DecimalField(decimal_places=0, max_digits=3)),
                ('weight_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weight_unit', models.CharField(choices=[('Grams', 'grams'), ('Kilograms', 'kilograms')], default='grams', max_length=10)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='bats/images/uploads/')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bat',
                'verbose_name_plural': 'Bats',
            },
        ),
    ]
