# Generated by Django 5.1.2 on 2025-03-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0002_remove_bat_image_bat_images_batgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batgallery',
            options={'verbose_name': 'batgallery', 'verbose_name_plural': 'batgallery'},
        ),
    ]
