# Generated by Django 5.1.2 on 2025-03-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0003_alter_batgallery_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bat',
            old_name='images',
            new_name='image',
        ),
    ]
