# Generated by Django 5.1.2 on 2025-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bats', '0005_alter_bat_image_alter_batgallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batgallery',
            old_name='product',
            new_name='bat',
        ),
        migrations.AlterField(
            model_name='bat',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='bats/images/uploads'),
        ),
    ]
